version: '3'
services:
  myapp:
    image: pontomaster
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: db_pontomaster
    ports:
      - "3306:3306"
